spring:

  datasource:
    url: jdbc:h2:file:../api-cliente/dbteste
    username: root
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      properties.hibernate.show_sql: true
      properties.hibernate.format_sql: true
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2